USE ContosoRetailDW


SELECT TOP 100
	OS.DateKey
	,DATENAME(DAY,OS.DateKey) AS DAY
	,DATENAME(WEEKDAY,OS.DateKey) AS WEEKDAY_NAME
	,DATEPART(WEEKDAY,OS.DateKey) AS WEEKDAY_PART
	,DATENAME(MONTH,OS.DateKey) AS MONTH_NAME
	,DATEPART(MONTH,OS.DateKey) AS MONTH_PART
FROM
	FactOnlineSales AS OS
WHERE DATENAME(WEEKDAY,OS.DateKey) = 'friday'
ORDER BY DateKey ASC