

USE ContosoRetailDW

-- DATEDIFF (intervalo, data_inicio, data_final)

SELECT DATEDIFF (DAY, '09-10-2023', GETDATE()) AS DIA
SELECT DATEDIFF (MONTH, '04-10-2023', GETDATE()) AS MES
SELECT DATEDIFF (YEAR, '04-10-2021', GETDATE()) AS ANO

SELECT DISTINCT TOP 100
	S.DateKey
	,GETDATE() AS TODAY
	,DATEDIFF(DAY, S.DateKey, GETDATE()) AS DIA
FROM FactOnlineSales AS S
ORDER BY 1 DESC